"""Assemble a NASM patch source into a verified .patch file.

Usage:  python tools/asm2patch.py patches/src/NAME.asm [patches/NAME.patch]

Source format: everything before the first `;@` marker is a shared header
(equates, macros) included in every chunk. Each chunk starts with

    ;@ F000:9F24                 place this code at F000:9F24
    ;@ F000:9F24 max=0x80        ... and fail if it grows past 80h bytes
    ;@ F000:9F24 free            ... and require the original bytes to be 00

and is assembled on its own with `org` set to that offset, so absolute
addresses (call 0x4F60, jmp 0x91B0) are encoded correctly. Use equates in the
header to share addresses between chunks. `;;` comment lines directly after
the marker are copied into the .patch file.

Old bytes always come from the ORIGINAL image, so a generated patch applies
only to an unmodified ROM (apply_patch.py verifies this).
"""
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ORIGINAL = os.path.join(HERE, "..", "NCR-BIOS-517-0000672-VER2.03.00-U19.BIN")
NASM_CANDIDATES = [
    os.path.expandvars(r"%LOCALAPPDATA%\bin\NASM\nasm.exe"),
    r"C:\Program Files\NASM\nasm.exe",
    "nasm",
]
SEGS = {"F000": 0x10000, "FA40": 0x1A400, "E000": 0x00000, "E800": 0x08000}


def nasm():
    for c in NASM_CANDIDATES:
        if c == "nasm" or os.path.exists(c):
            return c
    raise SystemExit("nasm not found")


def image_offset(seg, off):
    return SEGS[seg] + off


def assemble(header, body, org, name):
    src = "bits 16\norg 0x%X\n%s\n%s\n" % (org, header, body)
    with tempfile.TemporaryDirectory() as d:
        a, b = os.path.join(d, "p.asm"), os.path.join(d, "p.bin")
        open(a, "w").write(src)
        r = subprocess.run([nasm(), "-f", "bin", "-o", b, a], capture_output=True, text=True)
        if r.returncode:
            raise SystemExit("nasm failed in chunk %s:\n%s" % (name, r.stderr))
        return open(b, "rb").read()


def build(src_path):
    text = open(src_path).read()
    parts = re.split(r"^;@\s*", text, flags=re.M)
    header, chunks = parts[0], parts[1:]
    rom = open(ORIGINAL, "rb").read()
    out = []
    title = [l[1:].strip() if l.startswith(";") else "" for l in header.splitlines()
             if l.startswith(";") and not l.startswith(";@")]
    out += ["# " + t if t else "#" for t in title]
    out.append("# Generated by tools/asm2patch.py from %s - edit the .asm, not this file."
               % os.path.relpath(src_path, os.path.join(HERE, "..")).replace("\\", "/"))
    placed = []
    for ch in chunks:
        first, _, body = ch.partition("\n")
        m = re.match(r"([0-9A-Fa-f]{4}):([0-9A-Fa-f]{4})(.*)", first.strip())
        if not m:
            raise SystemExit("bad marker: ;@ " + first)
        seg, off = m.group(1).upper(), int(m.group(2), 16)
        opts = m.group(3)
        mx = re.search(r"max=(0x[0-9A-Fa-f]+|\d+)", opts)
        code = assemble(header, body, off, first.strip())
        if mx and len(code) > int(mx.group(1), 0):
            raise SystemExit("chunk %s is %d bytes, max %s" % (first.strip(), len(code), mx.group(1)))
        at = image_offset(seg, off)
        old = rom[at:at + len(code)]
        if "free" in opts and any(old):
            raise SystemExit("chunk %s: target is not free (00) space" % first.strip())
        for a0, a1, n in placed:
            if at < a1 and a0 < at + len(code):
                raise SystemExit("chunk %s overlaps chunk %s" % (first.strip(), n))
        placed.append((at, at + len(code), first.strip()))
        out.append("")
        for l in body.splitlines():
            if l.startswith(";;"):
                out.append("#" + l[2:])
            elif l.strip():
                break
        for i in range(0, len(code), 16):
            o, n = old[i:i + 16], code[i:i + 16]
            if o == n:
                continue
            out.append("%s:%04X  %s  ->  %s" % (seg, off + i, o.hex(" ").upper(), n.hex(" ").upper()))
    return "\n".join(out) + "\n", placed


if __name__ == "__main__":
    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        HERE, "..", "patches", os.path.splitext(os.path.basename(src))[0] + ".patch")
    text, placed = build(src)
    open(dst, "w").write(text)
    total = sum(b - a for a, b, _ in placed)
    print("%s: %d chunk(s), %d bytes -> %s" % (os.path.basename(src), len(placed), total, dst))
